### ISSUE TITLE
howto run from root folder?

### ISSUE THREAD

**Issue by rusefillc** [chuckwagoncomputing/interactive-pinout#12]
the popular/default https://github.com/rusefi/adapters/blob/master/.github/workflows/gen-pinouts.yaml does not survive "connectors" folder being in the root folder of the repo

see https://github.com/rusefi/adapters/ - i took a healthily sample repo and moved folder up, things turned red

random change to add second star did not help https://github.com/rusefi/adapters/commit/c5e897c64b8226c7d4d4ac0c5a1bc7e3c2c355be

is it possible to adjust the "default" yaml to add support for connectors in root folder?

**Comment by chuckwagoncomputing** [comment]
I have created [a PR](https://github.com/rusefi/adapters/pull/1) for you.
