### ISSUE TITLE
template is not applied into HTML

### ISSUE THREAD

**Issue by rusefillc** [chuckwagoncomputing/interactive-pinout#13]
See https://github.com/rusefi/rusefi/blob/a4dfedbcec1ba35f4d1f538f2ff375f7362987ef/firmware/config/boards/hellen/hellen-honda-k/connectors/main.yaml#L223

```
  - pin: B17
    # H144_IN_IAT AIN14 PC3
    id: EFI_ADC_13
    class: analog_inputs
    ts_name: ___ IAT
    function: IAT
```

templating seems to work at least sometimes see https://github.com/rusefi/rusefi/blob/00e21362882ccb220150b97dea018f7aa669eb0a/firmware/tunerstudio/generated/rusefi_hellen-honda-k.ini#L92 with ``"B17 IAT"``

but HTML https://rusefi.com/docs/pinouts/hellen/hellen-honda-k/?connector=Honda-K&pin=B17 shows raw ``___ IAT``

![chrome_iIq4nwagOz](https://github.com/chuckwagoncomputing/interactive-pinout/assets/48498823/387ec682-a88e-4f6a-ada9-d65b34b11581)

**Comment by chuckwagoncomputing** [comment]
Fixed with 2.10
