### ISSUE TITLE
I can only click on one pin

### ISSUE THREAD

**Issue by rusefillc** [chuckwagoncomputing/interactive-pinout#14]
pinout definition https://github.com/rusefi/stim/tree/main/digital_inputs/connectors produces https://rusefi.com/docs/pinouts/stim/

clicking on any pin produces table above full pinout as expected

![image](https://github.com/chuckwagoncomputing/interactive-pinout/assets/48498823/e9504554-60ce-472c-b3c6-0fa1bf14f6b1)

but clicking any other pin next does not produce similar table for that other pin

![image](https://github.com/chuckwagoncomputing/interactive-pinout/assets/48498823/13f8a116-a4ec-459c-88a0-bfad7ee6902c)

work-around: hit F5 to refresh and click on whatever (one) pin again

**Comment by chuckwagoncomputing** [comment]
Looks like something is confusing the minifier. You can work around that with `debug: "true"` in the workflow until I get it figured out.

**Comment by rusefillc** [comment]
just confirming that https://github.com/rusefi/stim/commit/96152c581a383cd3b6963ee8217179f67ec73588 work-around has helped

**Comment by chuckwagoncomputing** [comment]
https://github.com/chuckwagoncomputing/interactive-pinout/commit/d23e8c0866c16bee779bd1871192f954f0435599 has kinda fixed it but there's still some weird minifying stuff that I think is fixed in https://github.com/tdewolff/minify/releases/tag/v2.20.6

**Comment by chuckwagoncomputing** [comment]
The latest release of minify has fixed this issue.
