### ISSUE TITLE
add validation of "type" field values

### ISSUE THREAD

**Issue by mi-hol** [chuckwagoncomputing/interactive-pinout#16]
There should be a list of allowed values for "type" field in documentation.
Meaning of the type values should be explained there too.
Used values should be validated against defined list in order to avoid errors in definition.

As I understand it, the currently allowed value list and meaning seems to be: 

- 5V (5V +)
- 12V (12V +)
- at (Analog Temperature Input)
- av (Analog Voltage Input (i.e. pressure))
- can (CANBUS)
- din (Digital trigger/switch input)
- etb (Electronic Throttle Body)
- gnd (Ground (-)) (Question: should this be flagged as warning with suggestion to separate into sgnd or pgnd?)
- hs (High side) (Question: identical to gp-high?)
- hl (???)
- sgnd (Sensor Ground (-))
- pgnd (Power Ground (-))
- gp_high (General Purpose - high side?)
- gp_low (General Purpose - low side?)
- gp_pp (General Purpose - push-pull (low and high side output, 600mA)
- hall (hall trigger sensor)
- ign (Ignition)
- inj (Injection)
- mr (???)
- ls (Low side) (Question: identical to gp-low?)
- TPS (Throttle Position Sensor)
- vr (variable-reluctance (VR) trigger sensor)
- usb (Universal Serial Bus)

**Comment by chuckwagoncomputing** [comment]
The "types" are defined by the project using interactive-pinout, e.g. for rusEFI in https://github.com/rusefi/rusefi/blob/master/.github/workflows/gen-pinouts.yaml.
I agree that documenting these could be useful for the rusEFI project, however, this repo is not the place to do it.

**Comment by mi-hol** [comment]
@chuckwagoncomputing please reopen, because currently "types" the referenced file are really hard to understand. A better reference is needed from my view that should be included or linked in the using repos. The "table" in first comment was the first trial to improve this open topic.
