### ISSUE TITLE
how does it decide on circle size?

### ISSUE THREAD

**Issue by rusefillc** [chuckwagoncomputing/interactive-pinout#20]
it's hard to see but there is C1 circle on the connector why is it so small? https://rusefi.com/docs/pinouts/uaefi/honda-obd1/?pin=C1

yaml looks normal to me
```
    - pin: B7
      x: 1070
      y: 260
    - pin: B8
      x: 1070
      y: 387

    - pin: C1
      x: 1853
      y: 260
    - pin: C3
      x: 1922
      y: 260
    - pin: C5
      x: 1995
      y: 260
    - pin: C7
      x: 2073
      y: 260
    - pin: C9
      x: 2145
      y: 260
    - pin: C11
      x: 2219
      y: 260


    - pin: C2
      x: 1853
      y: 387
    - pin: C4
      x: 1922
      y: 387
    - pin: C6
      x: 1995
      y: 387
    - pin: C8
      x: 2073
      y: 387
    - pin: C10
      x: 2145
      y: 387
    - pin: C12
      x: 2219
      y: 387
```

**Comment by chuckwagoncomputing** [comment]
1. Can I access the source to try building it myself? If not, can you build it with `debug: true`?
2. Is that path intended? `/uaefi/honda-obd1`

**Comment by rusefillc** [comment]
1. https://github.com/rusefi/rusefi-hardware/actions/runs/8196687347/job/22417412635
2. yes

**Comment by chuckwagoncomputing** [comment]
You have B1 through B7 defined twice, and B1 and B2 are at the same coordinates as C1 and C2.

**Comment by rusefillc** [comment]
@chuckwagoncomputing error if two pins are same exact coordinate?

**Comment by rusefillc** [comment]
@chuckwagoncomputing error if same pin twice?

**Comment by chuckwagoncomputing** [comment]
Working on erroring if same pin twice.

**Comment by chuckwagoncomputing** [comment]
Done: https://github.com/chuckwagoncomputing/rusefi-hardware/actions/runs/8197077300
