### ISSUE TITLE
s/ECU/device?

### ISSUE THREAD

**Issue by rusefillc** [chuckwagoncomputing/interactive-pinout#4]
readme says "ECU connector photo" but really is the whatever device see dashboard usage https://github.com/opelpanfan/car-dash-7 https://opelpanfan.github.io/car-dash-7/pinout/?connector=left23&pin=1

**Comment by chuckwagoncomputing** [comment]
Good catch, thank you!
Fixed with 62be04a7d49af1e427ff261a56e69be002b706dd
