### ISSUE TITLE
simplify maintenance of pinout docs via  "dynamic views" feature resolved

### ISSUE THREAD

**Issue by mi-hol** [chuckwagoncomputing/interactive-pinout#5]
The main document for pinouts is the YAML definition, but often multiple iterations are required to create a fully correct definition.
At the same time certain subsets of the definition "views" are required in docs to illustrate facts like grouping of all pins used for "power" or "ignition".
Currently  these views have to be created manually via a copy & paste process.
Unfortunately later changes in YAML need to be applied to these "disconnected copies" too.
There is a high risk of failure because original author(s) and maintainer(s) are frequently different persons.

This risk could be avoided by defining a "dynamic view" as a kind of query for the YAML definition that gets resolved into a static markdown text at time of document build/lint.

**Comment by mi-hol** [comment]
https://mdxjs.com/docs/extending-mdx/ could be an approach to implement this feature

**Comment by chuckwagoncomputing** [comment]
I think I understand now, but this is not within the scope of this tool.
This tool generates interactive pinouts with HTML/CSS/JS, not markdown files.

**Comment by mi-hol** [comment]
HTML can be embedded into 

Would the[ pick operator](https://mikefarah.gitbook.io/yq/operators/pick) be the mechanism to select the required fields?

**Comment by chuckwagoncomputing** [comment]
Maybe; try it and find out.
