### ISSUE TITLE
text selection glitch?

### ISSUE THREAD

**Issue by rusefillc** [chuckwagoncomputing/interactive-pinout#7]
I am failing to copy-paste text from interactive-pinout pages

https://rusefi.com/docs/pinouts/proteus/?connector=black23&pin=16

i mouse-double click on "can" in "type" column, text gets selected but then selection is gone?! :(
i use mouse trag to select "can bus low" and then selection is gone?

**Comment by chuckwagoncomputing** [comment]
Yep, this is because it's trying to handle clicks, which it probably shouldn't be, and as a result deleting and replacing the table. I'll fix that.

**Comment by chuckwagoncomputing** [comment]
Fixed.
