### ISSUE TITLE
was [pin url jumps from one connector to another] now please WARN/FAIL on sid duplicate

### ISSUE THREAD

**Issue by rusefillc** [chuckwagoncomputing/interactive-pinout#8]
open https://rusefi.com/docs/pinouts/proteus/

scroll to black35 connector
click on pin 1

result: browser shows https://rusefi.com/docs/pinouts/proteus/?connector=black23&pin=1 while black35 not black23 would be expected in the URL?

same does NOT happen with white35. is this something wrong with my input file or else?

**Comment by chuckwagoncomputing** [comment]
The bug is fixed, and I have added a warning for duplicate CIDs.
![image](https://github.com/chuckwagoncomputing/interactive-pinout/assets/1531127/10c85512-fc85-41bf-aeb3-14cc2c7a7365)
